stages:
  - build

build:
  stage: build
  when: manual
  tags:
    - dev
  only:
    - /^branch\/[\S]+/
  variables:
    VERSION: "v12.0"
  script:
    - docker build -f Dockerfile -t harbor.w.chime.me/crm/auto-ui:$VERSION .
    - docker rm -f auto-ui || true
    - docker run --init -d -p 8086:8086 --name auto-ui --restart=on-failure:5 --privileged -v /home/web/auto-ui/env.py:/usr/src/app/env.py -v /home/web/auto-ui/media:/usr/src/app/media -v /home/web/auto-ui/static:/usr/src/app/static -v /home/web/auto-ui/templates:/usr/src/app/templates harbor.w.chime.me/crm/auto-ui:$VERSION
    - docker push harbor.w.chime.me/crm/auto-ui:$VERSION
