# Generated by Django 4.2.1 on 2023-05-18 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('code', models.TextField()),
                ('operations', models.TextField()),
                ('has_norm', models.IntegerField(default=0)),
                ('is_running', models.IntegerField(default=0)),
                ('is_waiting', models.IntegerField(default=0)),
                ('last_succ', models.IntegerField(default=0)),
                ('run_log', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(max_length=200)),
                ('last_run_time', models.DateTimeField(auto_now_add=True)),
                ('last_comp_count', models.IntegerField(default=0)),
                ('last_error_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_index', models.IntegerField()),
                ('type', models.IntegerField(default=0)),
                ('ope_type', models.CharField(max_length=30)),
                ('ope_name', models.CharField(max_length=200)),
                ('open_url', models.CharField(max_length=1000)),
                ('find_type', models.CharField(max_length=20)),
                ('find_val', models.CharField(max_length=200)),
                ('input_val', models.CharField(max_length=255)),
                ('is_enter', models.IntegerField(default=0)),
                ('time_limit', models.IntegerField()),
                ('var_ope', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('other_process', models.IntegerField()),
                ('button', models.CharField(max_length=20)),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_handler.process')),
            ],
        ),
    ]
