# Generated by Django 4.2.1 on 2023-05-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='case',
            table='case',
        ),
        migrations.AlterModelTable(
            name='operation',
            table='operation',
        ),
        migrations.AlterModelTable(
            name='process',
            table='process',
        ),
    ]
