# Generated by Django 4.2.1 on 2023-05-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0002_alter_case_table_alter_operation_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='button',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='find_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='find_val',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='input_val',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='is_enter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='ope_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='open_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='other_process',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='time_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='var_ope',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
