# Generated by Django 4.2.1 on 2023-05-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0003_alter_operation_button_alter_operation_find_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_comp_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='last_error_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='last_run_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='run_log',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='describe',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
