# Generated by Django 4.2.1 on 2023-05-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0004_alter_case_last_comp_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='run_log',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
