# Generated by Django 4.2.1 on 2023-05-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_handler', '0005_alter_case_run_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_run_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
